name: "P6 GHA: Build"
description: "P6 GHA: Build"
author: "Philip M. Gollucci"

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: echo "This workflow intentionally does nothing and always passes."
